spring:
    application:
      name: employee-service

    datasource:
      url: jdbc:postgresql://localhost:5432/mac
      platform: POSTGRESQL
      username: postgres
      password: 123456

    jpa:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
      properties.hibernate.temp.use_jdbc_metadata_defaults: false


server:
  port: 8080